# Generated by Django 3.2.6 on 2021-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='your_question',
        ),
        migrations.AlterField(
            model_name='question',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
