# Generated by Django 3.2.6 on 2021-08-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210819_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
